
View current selection of records as:
<div class="btn-group" role="group" aria-label="...">
  <a href="/results.html?&layout=cdwa&format=xml&maximumrecords=-1&recordType=objects_1&query=<!--#4Dtext gsFunc_GetInfo ("Current Query String")-->"
      target="_blank" class="btn btn-outline-secondary">
      CDWA Lite XML
  </a>
  <a href="/results.html?&layout=lido&format=xml&maximumrecords=-1&recordType=objects_1&query=<!--#4Dtext gsFunc_GetInfo ("Current Query String")-->"
      target="_blank" class="btn btn-outline-secondary">
      LIDO XML
  </a>
  <a href="/results.html?&layout=vracore4&format=xml&maximumrecords=-1&recordType=objects_1&query=<!--#4Dtext gsFunc_GetInfo ("Current Query String")-->"
      target="_blank" class="btn btn-outline-secondary">
      VRA Core 4
  </a>
  <a href="/results.html?&layout=mods&format=xml&maximumrecords=-1&recordType=objects_1&query=<!--#4Dtext gsFunc_GetInfo ("Current Query String")-->"
      target="_blank" class="btn btn-outline-secondary">
      MODS XML
  </a>
  <a href="/results.html?&layout=objects&format=json&maximumrecords=-1&recordType=objects_1&query=<!--#4Dtext gsFunc_GetInfo ("Current Query String")-->"
      target="_blank" class="btn btn-outline-secondary">
      Objects JSON
  </a>
</div>
